### ISSUE TITLE
Play 2.5 incompatibility

### ISSUE THREAD

**Issue by niqdev** [qb-project/qbproject#57]
Hi,
upgrading our microservices from Play 2.4 to 2.5 we have the following error

```
DocumentValidationException:
DocumentDataErrors(Map(errors -> List(Unknown error in document validation)))
```

Debugging I've found that in `JsValueProcessor#processObject` this line
`val maybeValue = obj.get(attr.name)`
complain saying that `obj` doesn't have a `get` method throwing the exception above while I'm passing a valid `JsObject`

If you help me pointing in the right direction I will make a pull request fixing this issue.

Thanks!

**Comment by edgarmueller** [comment]
Hi @niqdev,
this is strange, as the get method is provided via an implicit class `JsObjectExtensions` in `schema/package.scala`. Also I couldn't reproduce any error after upgrading to 2.5. Could you perhaps provide more info? Also, may I ask if switching to [the schema validation library](https://github.com/eclipsesource/play-json-schema-validator) is an option, as we actively maintain that package?

**Comment by niqdev** [comment]
Hi @edgarmueller, I will have a look at `play-json-schema-validator` and switch to the new lib in case.
Thanks!
